name: Build & Test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Build
        run: zig build --build-file $PWD/tests/build.zig --summary all -freference-trace
      - name: Run
        if: ${{ failure() }}
        run: |
            zig build rtsan --build-file $PWD/tests/build.zig -freference-trace
            zig build asan --build-file $PWD/tests/build.zig -freference-trace