name: cross

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        targets:
          - x86_64-linux-gnu
          - x86_64-linux-musl
          - aarch64-linux-musl

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Download & Extract packages
        run: |
          sudo apt update && sudo apt install -y qemu-user-binfmt
      - name: Build Summary ${{ matrix.targets }}
        run: zig build --build-file $PWD/tests/build.zig --summary all -freference-trace -Dtarget=${{ matrix.targets }}
      - name: Run ${{ matrix.targets }}
        if: ${{ failure() }}
        run: zig build rtsan --build-file $PWD/tests/build.zig --summary all -freference-trace -Dtarget=${{ matrix.targets }}
